package deepthinking.fgi.dao.mapper;

import deepthinking.fgi.domain.TableFunc;
import deepthinking.fgi.domain.TableFuncCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TableFuncMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_func
     *
     * @mbg.generated
     */
    @SelectProvider(type=TableFuncSqlProvider.class, method="countByExample")
    long countByExample(TableFuncCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_func
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TableFuncSqlProvider.class, method="deleteByExample")
    int deleteByExample(TableFuncCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_func
     *
     * @mbg.generated
     */
    @Delete({
        "delete from table_func",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_func
     *
     * @mbg.generated
     */
    @Insert({
        "insert into table_func (ID, ModuleID, ",
        "VarName, VarType, ",
        "ValValue, Remark)",
        "values (#{id,jdbcType=INTEGER}, #{moduleid,jdbcType=INTEGER}, ",
        "#{varname,jdbcType=VARCHAR}, #{vartype,jdbcType=VARCHAR}, ",
        "#{valvalue,jdbcType=VARCHAR}, #{remark,jdbcType=VARCHAR})"
    })
    int insert(TableFunc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_func
     *
     * @mbg.generated
     */
    @InsertProvider(type=TableFuncSqlProvider.class, method="insertSelective")
    int insertSelective(TableFunc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_func
     *
     * @mbg.generated
     */
    @SelectProvider(type=TableFuncSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ModuleID", property="moduleid", jdbcType=JdbcType.INTEGER),
        @Result(column="VarName", property="varname", jdbcType=JdbcType.VARCHAR),
        @Result(column="VarType", property="vartype", jdbcType=JdbcType.VARCHAR),
        @Result(column="ValValue", property="valvalue", jdbcType=JdbcType.VARCHAR),
        @Result(column="Remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    List<TableFunc> selectByExample(TableFuncCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_func
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "ID, ModuleID, VarName, VarType, ValValue, Remark",
        "from table_func",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ModuleID", property="moduleid", jdbcType=JdbcType.INTEGER),
        @Result(column="VarName", property="varname", jdbcType=JdbcType.VARCHAR),
        @Result(column="VarType", property="vartype", jdbcType=JdbcType.VARCHAR),
        @Result(column="ValValue", property="valvalue", jdbcType=JdbcType.VARCHAR),
        @Result(column="Remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    TableFunc selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_func
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TableFuncSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TableFunc record, @Param("example") TableFuncCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_func
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TableFuncSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TableFunc record, @Param("example") TableFuncCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_func
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TableFuncSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TableFunc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_func
     *
     * @mbg.generated
     */
    @Update({
        "update table_func",
        "set ModuleID = #{moduleid,jdbcType=INTEGER},",
          "VarName = #{varname,jdbcType=VARCHAR},",
          "VarType = #{vartype,jdbcType=VARCHAR},",
          "ValValue = #{valvalue,jdbcType=VARCHAR},",
          "Remark = #{remark,jdbcType=VARCHAR}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TableFunc record);
}