package deepthinking.fgi.domain;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.List;

/**
 * 算法规则
 */
@ApiModel(value = "算法规则")
public class TableRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_role.ID
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "ID")
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_role.RoleName
     * 规则名称
     * @mbg.generated
     */
    @ApiModelProperty(value = "规则名称")
    private String rolename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_role.Des
     * 规则描述
     * @mbg.generated
     */
    @ApiModelProperty(value = "规则描述")
    private String des;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_role.Remark
     * 备注
     * @mbg.generated
     */
    @ApiModelProperty(value = "备注")
    private String remark;

    /**
     * 算法算子关系列表
     */
    @ApiModelProperty(hidden = true)
    private List<TableAlgorithmrole> tableAlgorithmroleList;

    /**
     * @Description 导入辅助字段
     * @Author p.ww
     * @Date 2020/2/25
     **/
    private Integer tno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_role.ID
     *
     * @return the value of table_role.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_role.ID
     *
     * @param id the value for table_role.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_role.RoleName
     *
     * @return the value of table_role.RoleName
     *
     * @mbg.generated
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_role.RoleName
     *
     * @param rolename the value for table_role.RoleName
     *
     * @mbg.generated
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_role.Des
     *
     * @return the value of table_role.Des
     *
     * @mbg.generated
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_role.Des
     *
     * @param des the value for table_role.Des
     *
     * @mbg.generated
     */
    public void setDes(String des) {
        this.des = des == null ? null : des.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_role.Remark
     *
     * @return the value of table_role.Remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_role.Remark
     *
     * @param remark the value for table_role.Remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    public List<TableAlgorithmrole> getTableAlgorithmroleList() {
        return tableAlgorithmroleList;
    }

    public void setTableAlgorithmroleList(List<TableAlgorithmrole> tableAlgorithmroleList) {
        this.tableAlgorithmroleList = tableAlgorithmroleList;
    }

    public Integer getTno() {
        return tno;
    }

    public void setTno(Integer tno) {
        this.tno = tno;
    }
}