package deepthinking.fgi.domain;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * 算子用户关系
 */
@ApiModel(value = "算子用户关系")
public class TableModuleuserrelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_moduleuserrelation.ID
     *
     * @mbg.generated
     */
    @ApiModelProperty("ID")
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_moduleuserrelation.ModuleID
     * 算子ID
     * @mbg.generated
     */
    @ApiModelProperty("算子ID")
    private Integer moduleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_moduleuserrelation.UserName
     * 用户名
     * @mbg.generated
     */
    @ApiModelProperty("用户名")
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_moduleuserrelation.Remark
     * 备注
     * @mbg.generated
     */
    @ApiModelProperty("备注")
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_moduleuserrelation.ID
     *
     * @return the value of table_moduleuserrelation.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_moduleuserrelation.ID
     *
     * @param id the value for table_moduleuserrelation.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_moduleuserrelation.ModuleID
     *
     * @return the value of table_moduleuserrelation.ModuleID
     *
     * @mbg.generated
     */
    public Integer getModuleid() {
        return moduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_moduleuserrelation.ModuleID
     *
     * @param moduleid the value for table_moduleuserrelation.ModuleID
     *
     * @mbg.generated
     */
    public void setModuleid(Integer moduleid) {
        this.moduleid = moduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_moduleuserrelation.UserName
     *
     * @return the value of table_moduleuserrelation.UserName
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_moduleuserrelation.UserName
     *
     * @param username the value for table_moduleuserrelation.UserName
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_moduleuserrelation.Remark
     *
     * @return the value of table_moduleuserrelation.Remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_moduleuserrelation.Remark
     *
     * @param remark the value for table_moduleuserrelation.Remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}