package deepthinking.fgi.domain;

public class TDictionaryValue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary_value.dic_value_code
     *
     * @mbg.generated
     */
    private String dicValueCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary_value.dic_code
     *
     * @mbg.generated
     */
    private Integer dicCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary_value.dic_value_name
     *
     * @mbg.generated
     */
    private String dicValueName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary_value.dic_value_comment
     *
     * @mbg.generated
     */
    private String dicValueComment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary_value.dic_value_code
     *
     * @return the value of t_dictionary_value.dic_value_code
     *
     * @mbg.generated
     */
    public String getDicValueCode() {
        return dicValueCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary_value.dic_value_code
     *
     * @param dicValueCode the value for t_dictionary_value.dic_value_code
     *
     * @mbg.generated
     */
    public void setDicValueCode(String dicValueCode) {
        this.dicValueCode = dicValueCode == null ? null : dicValueCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary_value.dic_code
     *
     * @return the value of t_dictionary_value.dic_code
     *
     * @mbg.generated
     */
    public Integer getDicCode() {
        return dicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary_value.dic_code
     *
     * @param dicCode the value for t_dictionary_value.dic_code
     *
     * @mbg.generated
     */
    public void setDicCode(Integer dicCode) {
        this.dicCode = dicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary_value.dic_value_name
     *
     * @return the value of t_dictionary_value.dic_value_name
     *
     * @mbg.generated
     */
    public String getDicValueName() {
        return dicValueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary_value.dic_value_name
     *
     * @param dicValueName the value for t_dictionary_value.dic_value_name
     *
     * @mbg.generated
     */
    public void setDicValueName(String dicValueName) {
        this.dicValueName = dicValueName == null ? null : dicValueName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary_value.dic_value_comment
     *
     * @return the value of t_dictionary_value.dic_value_comment
     *
     * @mbg.generated
     */
    public String getDicValueComment() {
        return dicValueComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary_value.dic_value_comment
     *
     * @param dicValueComment the value for t_dictionary_value.dic_value_comment
     *
     * @mbg.generated
     */
    public void setDicValueComment(String dicValueComment) {
        this.dicValueComment = dicValueComment == null ? null : dicValueComment.trim();
    }
}