package deepthinking.fgi.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import deepthinking.fgi.domain.TDatashieldDevice;
import deepthinking.fgi.domain.TDatashieldDeviceCriteria;
import deepthinking.fgi.dto.frontend.DsDeviceQryCriteria;
import deepthinking.fgi.dto.frontend.TDatashieldDeviceDto;

public interface TDatashieldDeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datashield_device
     *
     * @mbg.generated
     */
    @SelectProvider(type=TDatashieldDeviceSqlProvider.class, method="countByExample")
    long countByExample(TDatashieldDeviceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datashield_device
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TDatashieldDeviceSqlProvider.class, method="deleteByExample")
    int deleteByExample(TDatashieldDeviceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datashield_device
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_datashield_device",
        "where dsdevice_code = #{dsdeviceCode,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String dsdeviceCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datashield_device
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_datashield_device (dsdevice_code, device_type_code, ",
        "organization_code, dsdevice_name, ",
        "dsdevice_model, dsdevice_serial_no, ",
        "device_status_code)",
        "values (#{dsdeviceCode,jdbcType=VARCHAR}, #{deviceTypeCode,jdbcType=VARCHAR}, ",
        "#{organizationCode,jdbcType=INTEGER}, #{dsdeviceName,jdbcType=VARCHAR}, ",
        "#{dsdeviceModel,jdbcType=VARCHAR}, #{dsdeviceSerialNo,jdbcType=VARCHAR}, ",
        "#{deviceStatusCode,jdbcType=VARCHAR})"
    })
    int insert(TDatashieldDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datashield_device
     *
     * @mbg.generated
     */
    @InsertProvider(type=TDatashieldDeviceSqlProvider.class, method="insertSelective")
    int insertSelective(TDatashieldDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datashield_device
     *
     * @mbg.generated
     */
    @SelectProvider(type=TDatashieldDeviceSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="dsdevice_code", property="dsdeviceCode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="device_type_code", property="deviceTypeCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="organization_code", property="organizationCode", jdbcType=JdbcType.INTEGER),
        @Result(column="dsdevice_name", property="dsdeviceName", jdbcType=JdbcType.VARCHAR),
        @Result(column="dsdevice_model", property="dsdeviceModel", jdbcType=JdbcType.VARCHAR),
        @Result(column="dsdevice_serial_no", property="dsdeviceSerialNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="device_status_code", property="deviceStatusCode", jdbcType=JdbcType.VARCHAR)
    })
    List<TDatashieldDevice> selectByExample(TDatashieldDeviceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datashield_device
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "dsdevice_code, device_type_code, organization_code, dsdevice_name, dsdevice_model, ",
        "dsdevice_serial_no, device_status_code",
        "from t_datashield_device",
        "where dsdevice_code = #{dsdeviceCode,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="dsdevice_code", property="dsdeviceCode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="device_type_code", property="deviceTypeCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="organization_code", property="organizationCode", jdbcType=JdbcType.INTEGER),
        @Result(column="dsdevice_name", property="dsdeviceName", jdbcType=JdbcType.VARCHAR),
        @Result(column="dsdevice_model", property="dsdeviceModel", jdbcType=JdbcType.VARCHAR),
        @Result(column="dsdevice_serial_no", property="dsdeviceSerialNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="device_status_code", property="deviceStatusCode", jdbcType=JdbcType.VARCHAR)
    })
    TDatashieldDevice selectByPrimaryKey(String dsdeviceCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datashield_device
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TDatashieldDeviceSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TDatashieldDevice record, @Param("example") TDatashieldDeviceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datashield_device
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TDatashieldDeviceSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TDatashieldDevice record, @Param("example") TDatashieldDeviceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datashield_device
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TDatashieldDeviceSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TDatashieldDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datashield_device
     *
     * @mbg.generated
     */
    @Update({
        "update t_datashield_device",
        "set device_type_code = #{deviceTypeCode,jdbcType=VARCHAR},",
          "organization_code = #{organizationCode,jdbcType=INTEGER},",
          "dsdevice_name = #{dsdeviceName,jdbcType=VARCHAR},",
          "dsdevice_model = #{dsdeviceModel,jdbcType=VARCHAR},",
          "dsdevice_serial_no = #{dsdeviceSerialNo,jdbcType=VARCHAR},",
          "device_status_code = #{deviceStatusCode,jdbcType=VARCHAR}",
          "dsdevice_code = #{dsdeviceCode,jdbcType=VARCHAR}",
        "where dsdevice_key = #{dsdeviceKey,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TDatashieldDevice record);
    
    @SelectProvider(type=TDatashieldDeviceSqlProvider.class, method="selectAllDSDevices")
    @Results({
    	@Result(column="dsdevice_key", property="dsdeviceKey", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="dsdevice_code", property="dsdeviceCode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="dsdevice_name", property="dsdeviceName", jdbcType=JdbcType.VARCHAR),
        @Result(column="device_type_code", property="deviceTypeCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="organization_code", property="organizationCode", jdbcType=JdbcType.INTEGER),
        @Result(column="orgnization_name", property="orgnizationName", jdbcType=JdbcType.VARCHAR),
        @Result(column="dsdevice_name", property="dsdeviceName", jdbcType=JdbcType.VARCHAR),
        @Result(column="dsdevice_model", property="dsdeviceModel", jdbcType=JdbcType.VARCHAR),
        @Result(column="dsdevice_serial_no", property="dsdeviceSerialNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="device_status_code", property="deviceStatusCode", jdbcType=JdbcType.VARCHAR)
    })
    
    List<TDatashieldDeviceDto> selectAllDSDevices(DsDeviceQryCriteria queryParams);
    
    @SelectProvider(type=TDatashieldDeviceSqlProvider.class, method="selectDsDeviceLogs")
    @Results({
        @Result(column="dsdevice_code", property="dsdeviceCode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="device_type_code", property="deviceTypeCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="organization_code", property="organizationCode", jdbcType=JdbcType.INTEGER),
        @Result(column="dsdevice_name", property="dsdeviceName", jdbcType=JdbcType.VARCHAR),
        @Result(column="dsdevice_model", property="dsdeviceModel", jdbcType=JdbcType.VARCHAR),
        @Result(column="dsdevice_serial_no", property="dsdeviceSerialNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="device_status_code", property="deviceStatusCode", jdbcType=JdbcType.VARCHAR)
    })
    List<TDatashieldDevice> selectDsDeviceLogs(Object params);
}