package deepthinking.fgi.dao.mapper;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

import deepthinking.fgi.domain.TDictionaryValue;
import deepthinking.fgi.domain.TDictionaryValueCriteria;
import deepthinking.fgi.domain.TDictionaryValueCriteria.Criteria;
import deepthinking.fgi.domain.TDictionaryValueCriteria.Criterion;

public class TDictionaryValueSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary_value
     *
     * @mbg.generated
     */
    public String countByExample(TDictionaryValueCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("t_dictionary_value");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary_value
     *
     * @mbg.generated
     */
    public String deleteByExample(TDictionaryValueCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("t_dictionary_value");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary_value
     *
     * @mbg.generated
     */
    public String insertSelective(TDictionaryValue record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("t_dictionary_value");
        
        if (record.getDicValueCode() != null) {
            sql.VALUES("dic_value_code", "#{dicValueCode,jdbcType=VARCHAR}");
        }
        
        if (record.getDicCode() != null) {
            sql.VALUES("dic_code", "#{dicCode,jdbcType=INTEGER}");
        }
        
        if (record.getDicValueName() != null) {
            sql.VALUES("dic_value_name", "#{dicValueName,jdbcType=VARCHAR}");
        }
        
        if (record.getDicValueComment() != null) {
            sql.VALUES("dic_value_comment", "#{dicValueComment,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary_value
     *
     * @mbg.generated
     */
    public String selectByExample(TDictionaryValueCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("dic_value_code");
        } else {
            sql.SELECT("dic_value_code");
        }
        sql.SELECT("dic_code");
        sql.SELECT("dic_value_name");
        sql.SELECT("dic_value_comment");
        sql.FROM("t_dictionary_value");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary_value
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        TDictionaryValue record = (TDictionaryValue) parameter.get("record");
        TDictionaryValueCriteria example = (TDictionaryValueCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("t_dictionary_value");
        
        if (record.getDicValueCode() != null) {
            sql.SET("dic_value_code = #{record.dicValueCode,jdbcType=VARCHAR}");
        }
        
        if (record.getDicCode() != null) {
            sql.SET("dic_code = #{record.dicCode,jdbcType=INTEGER}");
        }
        
        if (record.getDicValueName() != null) {
            sql.SET("dic_value_name = #{record.dicValueName,jdbcType=VARCHAR}");
        }
        
        if (record.getDicValueComment() != null) {
            sql.SET("dic_value_comment = #{record.dicValueComment,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary_value
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("t_dictionary_value");
        
        sql.SET("dic_value_code = #{record.dicValueCode,jdbcType=VARCHAR}");
        sql.SET("dic_code = #{record.dicCode,jdbcType=INTEGER}");
        sql.SET("dic_value_name = #{record.dicValueName,jdbcType=VARCHAR}");
        sql.SET("dic_value_comment = #{record.dicValueComment,jdbcType=VARCHAR}");
        
        TDictionaryValueCriteria example = (TDictionaryValueCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary_value
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(TDictionaryValue record) {
        SQL sql = new SQL();
        sql.UPDATE("t_dictionary_value");
        
        if (record.getDicCode() != null) {
            sql.SET("dic_code = #{dicCode,jdbcType=INTEGER}");
        }
        
        if (record.getDicValueName() != null) {
            sql.SET("dic_value_name = #{dicValueName,jdbcType=VARCHAR}");
        }
        
        if (record.getDicValueComment() != null) {
            sql.SET("dic_value_comment = #{dicValueComment,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("dic_value_code = #{dicValueCode,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary_value
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, TDictionaryValueCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}