package deepthinking.fgi.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import deepthinking.fgi.domain.TDictionary;
import deepthinking.fgi.domain.TDictionaryCriteria;

public interface TDictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbg.generated
     */
    @SelectProvider(type=TDictionarySqlProvider.class, method="countByExample")
    long countByExample(TDictionaryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TDictionarySqlProvider.class, method="deleteByExample")
    int deleteByExample(TDictionaryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_dictionary",
        "where dic_code = #{dicCode,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer dicCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_dictionary (dic_code, dic_name)",
        "values (#{dicCode,jdbcType=INTEGER}, #{dicName,jdbcType=VARCHAR})"
    })
    int insert(TDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbg.generated
     */
    @InsertProvider(type=TDictionarySqlProvider.class, method="insertSelective")
    int insertSelective(TDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbg.generated
     */
    @SelectProvider(type=TDictionarySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="dic_code", property="dicCode", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="dic_name", property="dicName", jdbcType=JdbcType.VARCHAR)
    })
    List<TDictionary> selectByExample(TDictionaryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "dic_code, dic_name",
        "from t_dictionary",
        "where dic_code = #{dicCode,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="dic_code", property="dicCode", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="dic_name", property="dicName", jdbcType=JdbcType.VARCHAR)
    })
    TDictionary selectByPrimaryKey(Integer dicCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TDictionarySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TDictionary record, @Param("example") TDictionaryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TDictionarySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TDictionary record, @Param("example") TDictionaryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TDictionarySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbg.generated
     */
    @Update({
        "update t_dictionary",
        "set dic_name = #{dicName,jdbcType=VARCHAR}",
        "where dic_code = #{dicCode,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TDictionary record);
}