package deepthinking.fgi.dao.mapper;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

import deepthinking.fgi.domain.TInstrument;
import deepthinking.fgi.domain.TInstrumentCriteria;
import deepthinking.fgi.domain.TInstrumentCriteria.Criteria;
import deepthinking.fgi.domain.TInstrumentCriteria.Criterion;

public class TInstrumentSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_instrument
     *
     * @mbg.generated
     */
    public String countByExample(TInstrumentCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("t_instrument");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_instrument
     *
     * @mbg.generated
     */
    public String deleteByExample(TInstrumentCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("t_instrument");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_instrument
     *
     * @mbg.generated
     */
    public String insertSelective(TInstrument record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("t_instrument");
        
        if (record.getInstrumentCode() != null) {
            sql.VALUES("instrument_code", "#{instrumentCode,jdbcType=VARCHAR}");
        }
        
        if (record.getDeviceTypeCode() != null) {
            sql.VALUES("device_type_code", "#{deviceTypeCode,jdbcType=VARCHAR}");
        }
        
        if (record.getOrganizationCode() != null) {
            sql.VALUES("organization_code", "#{organizationCode,jdbcType=INTEGER}");
        }
        
        if (record.getInstrumentName() != null) {
            sql.VALUES("instrument_name", "#{instrumentName,jdbcType=VARCHAR}");
        }
        
        if (record.getInstrumentModel() != null) {
            sql.VALUES("instrument_model", "#{instrumentModel,jdbcType=VARCHAR}");
        }
        
        if (record.getDeviceStatusCode() != null) {
            sql.VALUES("device_status_code", "#{deviceStatusCode,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_instrument
     *
     * @mbg.generated
     */
    public String selectByExample(TInstrumentCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("instrument_code");
        } else {
            sql.SELECT("instrument_code");
        }
        sql.SELECT("device_type_code");
        sql.SELECT("organization_code");
        sql.SELECT("instrument_name");
        sql.SELECT("instrument_model");
        sql.SELECT("device_status_code");
        sql.FROM("t_instrument");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    public String selectAllInstruments(HashMap<String,String> queryParams){
        SQL sql = new SQL();

        sql.SELECT("t1.instrument_key");
        sql.SELECT("t1.instrument_code");
        sql.SELECT("t1.device_type_code");
        sql.SELECT("t1.organization_code");
        sql.SELECT("t2.orgnization_name");
        sql.SELECT("t1.instrument_name");
        sql.SELECT("t1.instrument_model");
        sql.SELECT("t1.device_status_code");
        sql.FROM("t_instrument t1, t_orgnization t2");
        
        StringBuilder sb = new StringBuilder();
        
        sb.append(" 1=1");
        
        if(null!=queryParams){
        	String deviceTypeCode = queryParams.get("deviceTypeCode");
            if(null!=deviceTypeCode){
            	sb.append(" and device_type_code = '");
            	sb.append(deviceTypeCode);
            	sb.append("'");
            }
        	String instrumentName = queryParams.get("instrumentName");
            if(null!=instrumentName){
            	sb.append(" and instrument_name like '%");
            	sb.append(instrumentName);
            	sb.append("%'");
            }
        	String orgnizationName = queryParams.get("orgnizationName");
            if(null!=orgnizationName){
            	sb.append(" and t2.orgnization_name like '%");
            	sb.append(orgnizationName);
            	sb.append("%'");
            }

        }
        sb.append(" and t1.organization_code = t2.orgnization_code ");
        
        sql.WHERE(sb.toString());
        sql.ORDER_BY("instrument_code");
 
        
        return sql.toString();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_instrument
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        TInstrument record = (TInstrument) parameter.get("record");
        TInstrumentCriteria example = (TInstrumentCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("t_instrument");
        
        if (record.getInstrumentCode() != null) {
            sql.SET("instrument_code = #{record.instrumentCode,jdbcType=VARCHAR}");
        }
        
        if (record.getDeviceTypeCode() != null) {
            sql.SET("device_type_code = #{record.deviceTypeCode,jdbcType=VARCHAR}");
        }
        
        if (record.getOrganizationCode() != null) {
            sql.SET("organization_code = #{record.organizationCode,jdbcType=INTEGER}");
        }
        
        if (record.getInstrumentName() != null) {
            sql.SET("instrument_name = #{record.instrumentName,jdbcType=VARCHAR}");
        }
        
        if (record.getInstrumentModel() != null) {
            sql.SET("instrument_model = #{record.instrumentModel,jdbcType=VARCHAR}");
        }
        
        if (record.getDeviceStatusCode() != null) {
            sql.SET("device_status_code = #{record.deviceStatusCode,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_instrument
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("t_instrument");
        
        sql.SET("instrument_code = #{record.instrumentCode,jdbcType=VARCHAR}");
        sql.SET("device_type_code = #{record.deviceTypeCode,jdbcType=VARCHAR}");
        sql.SET("organization_code = #{record.organizationCode,jdbcType=INTEGER}");
        sql.SET("instrument_name = #{record.instrumentName,jdbcType=VARCHAR}");
        sql.SET("instrument_model = #{record.instrumentModel,jdbcType=VARCHAR}");
        sql.SET("device_status_code = #{record.deviceStatusCode,jdbcType=VARCHAR}");
        
        TInstrumentCriteria example = (TInstrumentCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_instrument
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(TInstrument record) {
        SQL sql = new SQL();
        sql.UPDATE("t_instrument");
        
        if (record.getInstrumentKey() != null && record.getInstrumentCode() != null) {
            sql.SET("instrument_code = #{instrumentCode,jdbcType=VARCHAR}");
        }
        if (record.getDeviceTypeCode() != null) {
            sql.SET("device_type_code = #{deviceTypeCode,jdbcType=VARCHAR}");
        }
        
        if (record.getOrganizationCode() != null) {
            sql.SET("organization_code = #{organizationCode,jdbcType=INTEGER}");
        }
        
        if (record.getInstrumentName() != null) {
            sql.SET("instrument_name = #{instrumentName,jdbcType=VARCHAR}");
        }
        
        if (record.getInstrumentModel() != null) {
            sql.SET("instrument_model = #{instrumentModel,jdbcType=VARCHAR}");
        }
        
        if (record.getDeviceStatusCode() != null) {
            sql.SET("device_status_code = #{deviceStatusCode,jdbcType=VARCHAR}");
        }
        if (record.getInstrumentKey() != null) {
        	sql.WHERE("instrument_key = #{instrumentKey,jdbcType=INTEGER}");
        }
        if(record.getInstrumentKey() == null){
        	sql.WHERE("instrument_code = #{instrumentCode,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_instrument
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, TInstrumentCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}