package deepthinking.fgi.dao.mapper;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

import deepthinking.fgi.domain.TInspectionLine;
import deepthinking.fgi.domain.TInspectionLineCriteria;
import deepthinking.fgi.domain.TInspectionLineCriteria.Criteria;
import deepthinking.fgi.domain.TInspectionLineCriteria.Criterion;

public class TInspectionLineSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inspection_line
     *
     * @mbg.generated
     */
    public String countByExample(TInspectionLineCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("t_inspection_line");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inspection_line
     *
     * @mbg.generated
     */
    public String deleteByExample(TInspectionLineCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("t_inspection_line");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inspection_line
     *
     * @mbg.generated
     */
    public String insertSelective(TInspectionLine record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("t_inspection_line");
        
        if (record.getLineCode() != null) {
            sql.VALUES("line_code", "#{lineCode,jdbcType=INTEGER}");
        }
        
        if (record.getRegionCode() != null) {
            sql.VALUES("region_code", "#{regionCode,jdbcType=VARCHAR}");
        }
        
        if (record.getLineName() != null) {
            sql.VALUES("line_name", "#{lineName,jdbcType=VARCHAR}");
        }
        
        if (record.getDirection() != null) {
            sql.VALUES("direction", "#{direction,jdbcType=VARCHAR}");
        }
        
        if (record.getMileageStart() != null) {
            sql.VALUES("mileage_start", "#{mileageStart,jdbcType=VARCHAR}");
        }
        
        if (record.getMileageEnd() != null) {
            sql.VALUES("mileage_end", "#{mileageEnd,jdbcType=VARCHAR}");
        }
        
        if (record.getCompletionDate() != null) {
            sql.VALUES("completion_date", "#{completionDate,jdbcType=DATE}");
        }
        
        if (record.getOperationDate() != null) {
            sql.VALUES("operation_date", "#{operationDate,jdbcType=DATE}");
        }
        
        if (record.getDescription() != null) {
            sql.VALUES("description", "#{description,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inspection_line
     *
     * @mbg.generated
     */
    public String selectByExample(TInspectionLineCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("line_code");
        } else {
            sql.SELECT("line_code");
        }
        sql.SELECT("region_code");
        sql.SELECT("line_name");
        sql.SELECT("direction");
        sql.SELECT("mileage_start");
        sql.SELECT("mileage_end");
        sql.SELECT("completion_date");
        sql.SELECT("operation_date");
        sql.SELECT("description");
        sql.FROM("t_inspection_line");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inspection_line
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        TInspectionLine record = (TInspectionLine) parameter.get("record");
        TInspectionLineCriteria example = (TInspectionLineCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("t_inspection_line");
        
        if (record.getLineCode() != null) {
            sql.SET("line_code = #{record.lineCode,jdbcType=INTEGER}");
        }
        
        if (record.getRegionCode() != null) {
            sql.SET("region_code = #{record.regionCode,jdbcType=VARCHAR}");
        }
        
        if (record.getLineName() != null) {
            sql.SET("line_name = #{record.lineName,jdbcType=VARCHAR}");
        }
        
        if (record.getDirection() != null) {
            sql.SET("direction = #{record.direction,jdbcType=VARCHAR}");
        }
        
        if (record.getMileageStart() != null) {
            sql.SET("mileage_start = #{record.mileageStart,jdbcType=VARCHAR}");
        }
        
        if (record.getMileageEnd() != null) {
            sql.SET("mileage_end = #{record.mileageEnd,jdbcType=VARCHAR}");
        }
        
        if (record.getCompletionDate() != null) {
            sql.SET("completion_date = #{record.completionDate,jdbcType=DATE}");
        }
        
        if (record.getOperationDate() != null) {
            sql.SET("operation_date = #{record.operationDate,jdbcType=DATE}");
        }
        
        if (record.getDescription() != null) {
            sql.SET("description = #{record.description,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inspection_line
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("t_inspection_line");
        
        sql.SET("line_code = #{record.lineCode,jdbcType=INTEGER}");
        sql.SET("region_code = #{record.regionCode,jdbcType=VARCHAR}");
        sql.SET("line_name = #{record.lineName,jdbcType=VARCHAR}");
        sql.SET("direction = #{record.direction,jdbcType=VARCHAR}");
        sql.SET("mileage_start = #{record.mileageStart,jdbcType=VARCHAR}");
        sql.SET("mileage_end = #{record.mileageEnd,jdbcType=VARCHAR}");
        sql.SET("completion_date = #{record.completionDate,jdbcType=DATE}");
        sql.SET("operation_date = #{record.operationDate,jdbcType=DATE}");
        sql.SET("description = #{record.description,jdbcType=VARCHAR}");
        
        TInspectionLineCriteria example = (TInspectionLineCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inspection_line
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(TInspectionLine record) {
        SQL sql = new SQL();
        sql.UPDATE("t_inspection_line");
        
        if (record.getRegionCode() != null) {
            sql.SET("region_code = #{regionCode,jdbcType=VARCHAR}");
        }
        
        if (record.getLineName() != null) {
            sql.SET("line_name = #{lineName,jdbcType=VARCHAR}");
        }
        
        if (record.getDirection() != null) {
            sql.SET("direction = #{direction,jdbcType=VARCHAR}");
        }
        
        if (record.getMileageStart() != null) {
            sql.SET("mileage_start = #{mileageStart,jdbcType=VARCHAR}");
        }
        
        if (record.getMileageEnd() != null) {
            sql.SET("mileage_end = #{mileageEnd,jdbcType=VARCHAR}");
        }
        
        if (record.getCompletionDate() != null) {
            sql.SET("completion_date = #{completionDate,jdbcType=DATE}");
        }
        
        if (record.getOperationDate() != null) {
            sql.SET("operation_date = #{operationDate,jdbcType=DATE}");
        }
        
        if (record.getDescription() != null) {
            sql.SET("description = #{description,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("line_code = #{lineCode,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inspection_line
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, TInspectionLineCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}