package deepthinking.fgi.dao.mapper;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

import deepthinking.fgi.domain.TOrgnization;
import deepthinking.fgi.domain.TOrgnizationCriteria;
import deepthinking.fgi.domain.TOrgnizationCriteria.Criteria;
import deepthinking.fgi.domain.TOrgnizationCriteria.Criterion;

public class TOrgnizationSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orgnization
     *
     * @mbg.generated
     */
    public String countByExample(TOrgnizationCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("t_orgnization");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orgnization
     *
     * @mbg.generated
     */
    public String deleteByExample(TOrgnizationCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("t_orgnization");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orgnization
     *
     * @mbg.generated
     */
    public String insertSelective(TOrgnization record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("t_orgnization");
        
        if (record.getOrgnizationCode() != null) {
            sql.VALUES("orgnization_code", "#{orgnizationCode,jdbcType=INTEGER}");
        }
        
        if (record.getOrgnizationName() != null) {
            sql.VALUES("orgnization_name", "#{orgnizationName,jdbcType=VARCHAR}");
        }
        
        if (record.getOrgnizationDirector() != null) {
            sql.VALUES("orgnization_director", "#{orgnizationDirector,jdbcType=VARCHAR}");
        }
        
        if (record.getOrgnizationDegree() != null) {
            sql.VALUES("orgnization_degree", "#{orgnizationDegree,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orgnization
     *
     * @mbg.generated
     */
    public String selectByExample(TOrgnizationCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("orgnization_code");
        } else {
            sql.SELECT("orgnization_code");
        }
        sql.SELECT("orgnization_name");
        sql.SELECT("orgnization_director");
        sql.SELECT("orgnization_degree");
        sql.FROM("t_orgnization");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    public String selectAllOrgnizations(HashMap<String,String> queryParams){
        SQL sql = new SQL();

        sql.SELECT("orgnization_code");
        sql.SELECT("orgnization_name");
        sql.SELECT("orgnization_director");
        sql.SELECT("orgnization_degree");
        sql.FROM("t_orgnization");
        
        StringBuilder sb = new StringBuilder();
        
        sb.append(" 1=1");
        
        if(null!=queryParams){
        	String orgnizationName = queryParams.get("orgnizationName");
            if(null!=orgnizationName){
            	sb.append(" and orgnization_name like '%");
            	sb.append(orgnizationName);
            	sb.append("%'");
            }
            String orgnizationDegree = queryParams.get("orgnizationDegree");
            if(null!=orgnizationDegree){
            	sb.append(" and orgnization_degree = '");
            	sb.append(orgnizationDegree);
            	sb.append("'");
            }
        }

        sql.WHERE(sb.toString());
        sql.ORDER_BY("orgnization_code");
 
        
        return sql.toString();
    }
    
    
    public String checkOrgnizationName(HashMap<String,String> queryParams){
        SQL sql = new SQL();

        sql.SELECT("orgnization_code");
        sql.FROM("t_orgnization");
        
        StringBuilder sb = new StringBuilder();
        
        sb.append(" 1=1");
        
        if(null!=queryParams){
        	String orgnizationName = queryParams.get("orgnizationName");
            if(null!=orgnizationName){
            	sb.append(" and orgnization_name = '");
            	sb.append(orgnizationName);
            	sb.append("'");
            }
            Object orgnizationCode = queryParams.get("orgnizationCode");
            if(null!=orgnizationCode){
            	sb.append(" and orgnization_code <> ");
            	sb.append((Integer)orgnizationCode);
            	sb.append("");
            }
        }

        sql.WHERE(sb.toString());
        sql.ORDER_BY("orgnization_code");
 
        
        return sql.toString();
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orgnization
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        TOrgnization record = (TOrgnization) parameter.get("record");
        TOrgnizationCriteria example = (TOrgnizationCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("t_orgnization");
        
        if (record.getOrgnizationCode() != null) {
            sql.SET("orgnization_code = #{record.orgnizationCode,jdbcType=INTEGER}");
        }
        
        if (record.getOrgnizationName() != null) {
            sql.SET("orgnization_name = #{record.orgnizationName,jdbcType=VARCHAR}");
        }
        
        if (record.getOrgnizationDirector() != null) {
            sql.SET("orgnization_director = #{record.orgnizationDirector,jdbcType=VARCHAR}");
        }
        
        if (record.getOrgnizationDegree() != null) {
            sql.SET("orgnization_degree = #{record.orgnizationDegree,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orgnization
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("t_orgnization");
        
        sql.SET("orgnization_code = #{record.orgnizationCode,jdbcType=INTEGER}");
        sql.SET("orgnization_name = #{record.orgnizationName,jdbcType=VARCHAR}");
        sql.SET("orgnization_director = #{record.orgnizationDirector,jdbcType=VARCHAR}");
        sql.SET("orgnization_degree = #{record.orgnizationDegree,jdbcType=VARCHAR}");
        
        TOrgnizationCriteria example = (TOrgnizationCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orgnization
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(TOrgnization record) {
        SQL sql = new SQL();
        sql.UPDATE("t_orgnization");
        
        if (record.getOrgnizationName() != null) {
            sql.SET("orgnization_name = #{orgnizationName,jdbcType=VARCHAR}");
        }
        
        if (record.getOrgnizationDirector() != null) {
            sql.SET("orgnization_director = #{orgnizationDirector,jdbcType=VARCHAR}");
        }
        
        if (record.getOrgnizationDegree() != null) {
            sql.SET("orgnization_degree = #{orgnizationDegree,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("orgnization_code = #{orgnizationCode,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orgnization
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, TOrgnizationCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}