package deepthinking.fgi.dao.mapper;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

import deepthinking.fgi.domain.TStaff;
import deepthinking.fgi.domain.TStaffCriteria;
import deepthinking.fgi.domain.TStaffCriteria.Criteria;
import deepthinking.fgi.domain.TStaffCriteria.Criterion;

public class TStaffSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff
     *
     * @mbg.generated
     */
    public String countByExample(TStaffCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("t_staff");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff
     *
     * @mbg.generated
     */
    public String deleteByExample(TStaffCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("t_staff");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff
     *
     * @mbg.generated
     */
    public String insertSelective(TStaff record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("t_staff");
        
        if (record.getStaffCode() != null) {
            sql.VALUES("staff_code", "#{staffCode,jdbcType=INTEGER}");
        }
        
        if (record.getOrganizationCode() != null) {
            sql.VALUES("organization_code", "#{organizationCode,jdbcType=INTEGER}");
        }
        
        if (record.getStaffName() != null) {
            sql.VALUES("staff_name", "#{staffName,jdbcType=VARCHAR}");
        }
        
        if (record.getStaffNumber() != null) {
            sql.VALUES("staff_number", "#{staffNumber,jdbcType=VARCHAR}");
        }
        
        if (record.getStaffRole() != null) {
            sql.VALUES("staff_role", "#{staffRole,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff
     *
     * @mbg.generated
     */
    public String selectByExample(TStaffCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("staff_code");
        } else {
            sql.SELECT("staff_code");
        }
        sql.SELECT("organization_code");
        sql.SELECT("staff_name");
        sql.SELECT("staff_number");
        sql.SELECT("staff_role");
        sql.FROM("t_staff");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    public String selectAllStaffs(HashMap<String,String> queryParams){
        SQL sql1 = new SQL();
        SQL sql2 = new SQL();
        
        sql1.SELECT_DISTINCT("t1.staff_code");
        sql1.SELECT("t1.organization_code");
        sql1.SELECT("t2.orgnization_name");
        sql1.SELECT("t1.staff_name");
        sql1.SELECT("t1.staff_number");
        sql1.SELECT("t1.staff_role");
        sql1.SELECT("t1.staff_pwd");
        sql1.FROM("t_staff t1,t_orgnization t2");

        StringBuilder sb1 = new StringBuilder();
        sb1.append(" 1=1");
        StringBuilder sb2 = new StringBuilder();
        sb2.append(" 1=1");
        
        if(null!=queryParams){
        	String staffName = queryParams.get("staffName");
            if(null!=staffName){
            	sb1.append(" and t1.staff_name like '%");
            	sb1.append(staffName);
            	sb1.append("%'");
            	sb2.append(" and t1.staff_name like '%");
            	sb2.append(staffName);
            	sb2.append("%'");
            }
        	String orgnizationName = queryParams.get("orgnizationName");
            if(null!=orgnizationName){
            	sb1.append(" and t2.orgnization_name like '%");
            	sb1.append(orgnizationName);
            	sb1.append("%'");
            }else{
                sql2.SELECT_DISTINCT(" t1.staff_code");
                sql2.SELECT("t1.organization_code");
                sql2.SELECT("t1.organization_code AS orgnization_name");
                sql2.SELECT("t1.staff_name");
                sql2.SELECT("t1.staff_number");
                sql2.SELECT("t1.staff_role");
                sql2.SELECT("t1.staff_pwd");
                sql2.FROM("t_staff t1");
                sb2.append(" and t1.organization_code is NULL");
                sql2.WHERE(sb2.toString());
            }
        }
        sb1.append(" and t1.organization_code = t2.orgnization_code");
        sql1.WHERE(sb1.toString()); 
 
        
        return sql2.toString().length()>0?(sql1.toString()+" UNION "+sql2.toString()):sql1.toString();
    }
    
    public String checkStaffNumber(HashMap<String,String> queryParams){
        SQL sql = new SQL();

        sql.SELECT("staff_number");
        sql.FROM("t_staff");
        
        StringBuilder sb = new StringBuilder();
        
        sb.append(" 1=1");
        
        if(null!=queryParams){
        	String staffNumber = queryParams.get("staffNumber");
            if(null!=staffNumber){
            	sb.append(" and staff_number = '");
            	sb.append(staffNumber);
            	sb.append("'");
            }
        	Object staffCode = queryParams.get("staffCode");
            if(null!=staffCode){
            	sb.append(" and staff_code <> ");
            	sb.append((Integer)staffCode);
            	sb.append("");
            }
        }

        sql.WHERE(sb.toString());
 
        
        return sql.toString();
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        TStaff record = (TStaff) parameter.get("record");
        TStaffCriteria example = (TStaffCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("t_staff");
        
        if (record.getStaffCode() != null) {
            sql.SET("staff_code = #{record.staffCode,jdbcType=INTEGER}");
        }
        
        if (record.getOrganizationCode() != null) {
            sql.SET("organization_code = #{record.organizationCode,jdbcType=INTEGER}");
        }
        
        if (record.getStaffName() != null) {
            sql.SET("staff_name = #{record.staffName,jdbcType=VARCHAR}");
        }
        
        if (record.getStaffNumber() != null) {
            sql.SET("staff_number = #{record.staffNumber,jdbcType=VARCHAR}");
        }
        
        if (record.getStaffRole() != null) {
            sql.SET("staff_role = #{record.staffRole,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("t_staff");
        
        sql.SET("staff_code = #{record.staffCode,jdbcType=INTEGER}");
        sql.SET("organization_code = #{record.organizationCode,jdbcType=INTEGER}");
        sql.SET("staff_name = #{record.staffName,jdbcType=VARCHAR}");
        sql.SET("staff_number = #{record.staffNumber,jdbcType=VARCHAR}");
        sql.SET("staff_role = #{record.staffRole,jdbcType=VARCHAR}");
        
        TStaffCriteria example = (TStaffCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(TStaff record) {
        SQL sql = new SQL();
        sql.UPDATE("t_staff");
        
        if (record.getOrganizationCode() != null) {
            sql.SET("organization_code = #{organizationCode,jdbcType=INTEGER}");
        }
        
        if (record.getStaffName() != null) {
            sql.SET("staff_name = #{staffName,jdbcType=VARCHAR}");
        }
        
        if (record.getStaffNumber() != null) {
            sql.SET("staff_number = #{staffNumber,jdbcType=VARCHAR}");
        }
        
        if (record.getStaffRole() != null) {
            sql.SET("staff_role = #{staffRole,jdbcType=VARCHAR}");
        }
        
        if (record.getStaffPwd() != null) {
            sql.SET("staff_pwd = #{staffPwd,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("staff_code = #{staffCode,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, TStaffCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}