package deepthinking.fgi.domain;

import java.util.ArrayList;
import java.util.List;

public class TInspectionPointCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_inspection_point
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_inspection_point
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_inspection_point
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inspection_point
     *
     * @mbg.generated
     */
    public TInspectionPointCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inspection_point
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inspection_point
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inspection_point
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inspection_point
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inspection_point
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inspection_point
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inspection_point
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inspection_point
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inspection_point
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inspection_point
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_inspection_point
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andInspectionPointCodeIsNull() {
            addCriterion("inspection_point_code is null");
            return (Criteria) this;
        }

        public Criteria andInspectionPointCodeIsNotNull() {
            addCriterion("inspection_point_code is not null");
            return (Criteria) this;
        }

        public Criteria andInspectionPointCodeEqualTo(Integer value) {
            addCriterion("inspection_point_code =", value, "inspectionPointCode");
            return (Criteria) this;
        }

        public Criteria andInspectionPointCodeNotEqualTo(Integer value) {
            addCriterion("inspection_point_code <>", value, "inspectionPointCode");
            return (Criteria) this;
        }

        public Criteria andInspectionPointCodeGreaterThan(Integer value) {
            addCriterion("inspection_point_code >", value, "inspectionPointCode");
            return (Criteria) this;
        }

        public Criteria andInspectionPointCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("inspection_point_code >=", value, "inspectionPointCode");
            return (Criteria) this;
        }

        public Criteria andInspectionPointCodeLessThan(Integer value) {
            addCriterion("inspection_point_code <", value, "inspectionPointCode");
            return (Criteria) this;
        }

        public Criteria andInspectionPointCodeLessThanOrEqualTo(Integer value) {
            addCriterion("inspection_point_code <=", value, "inspectionPointCode");
            return (Criteria) this;
        }

        public Criteria andInspectionPointCodeIn(List<Integer> values) {
            addCriterion("inspection_point_code in", values, "inspectionPointCode");
            return (Criteria) this;
        }

        public Criteria andInspectionPointCodeNotIn(List<Integer> values) {
            addCriterion("inspection_point_code not in", values, "inspectionPointCode");
            return (Criteria) this;
        }

        public Criteria andInspectionPointCodeBetween(Integer value1, Integer value2) {
            addCriterion("inspection_point_code between", value1, value2, "inspectionPointCode");
            return (Criteria) this;
        }

        public Criteria andInspectionPointCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("inspection_point_code not between", value1, value2, "inspectionPointCode");
            return (Criteria) this;
        }

        public Criteria andLineCodeIsNull() {
            addCriterion("line_code is null");
            return (Criteria) this;
        }

        public Criteria andLineCodeIsNotNull() {
            addCriterion("line_code is not null");
            return (Criteria) this;
        }

        public Criteria andLineCodeEqualTo(Integer value) {
            addCriterion("line_code =", value, "lineCode");
            return (Criteria) this;
        }

        public Criteria andLineCodeNotEqualTo(Integer value) {
            addCriterion("line_code <>", value, "lineCode");
            return (Criteria) this;
        }

        public Criteria andLineCodeGreaterThan(Integer value) {
            addCriterion("line_code >", value, "lineCode");
            return (Criteria) this;
        }

        public Criteria andLineCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("line_code >=", value, "lineCode");
            return (Criteria) this;
        }

        public Criteria andLineCodeLessThan(Integer value) {
            addCriterion("line_code <", value, "lineCode");
            return (Criteria) this;
        }

        public Criteria andLineCodeLessThanOrEqualTo(Integer value) {
            addCriterion("line_code <=", value, "lineCode");
            return (Criteria) this;
        }

        public Criteria andLineCodeIn(List<Integer> values) {
            addCriterion("line_code in", values, "lineCode");
            return (Criteria) this;
        }

        public Criteria andLineCodeNotIn(List<Integer> values) {
            addCriterion("line_code not in", values, "lineCode");
            return (Criteria) this;
        }

        public Criteria andLineCodeBetween(Integer value1, Integer value2) {
            addCriterion("line_code between", value1, value2, "lineCode");
            return (Criteria) this;
        }

        public Criteria andLineCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("line_code not between", value1, value2, "lineCode");
            return (Criteria) this;
        }

        public Criteria andDirectionIsNull() {
            addCriterion("direction is null");
            return (Criteria) this;
        }

        public Criteria andDirectionIsNotNull() {
            addCriterion("direction is not null");
            return (Criteria) this;
        }

        public Criteria andDirectionEqualTo(String value) {
            addCriterion("direction =", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotEqualTo(String value) {
            addCriterion("direction <>", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionGreaterThan(String value) {
            addCriterion("direction >", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionGreaterThanOrEqualTo(String value) {
            addCriterion("direction >=", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionLessThan(String value) {
            addCriterion("direction <", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionLessThanOrEqualTo(String value) {
            addCriterion("direction <=", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionLike(String value) {
            addCriterion("direction like", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotLike(String value) {
            addCriterion("direction not like", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionIn(List<String> values) {
            addCriterion("direction in", values, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotIn(List<String> values) {
            addCriterion("direction not in", values, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionBetween(String value1, String value2) {
            addCriterion("direction between", value1, value2, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotBetween(String value1, String value2) {
            addCriterion("direction not between", value1, value2, "direction");
            return (Criteria) this;
        }

        public Criteria andInspectionPointTypeCodeIsNull() {
            addCriterion("inspection_point_type_code is null");
            return (Criteria) this;
        }

        public Criteria andInspectionPointTypeCodeIsNotNull() {
            addCriterion("inspection_point_type_code is not null");
            return (Criteria) this;
        }

        public Criteria andInspectionPointTypeCodeEqualTo(String value) {
            addCriterion("inspection_point_type_code =", value, "inspectionPointTypeCode");
            return (Criteria) this;
        }

        public Criteria andInspectionPointTypeCodeNotEqualTo(String value) {
            addCriterion("inspection_point_type_code <>", value, "inspectionPointTypeCode");
            return (Criteria) this;
        }

        public Criteria andInspectionPointTypeCodeGreaterThan(String value) {
            addCriterion("inspection_point_type_code >", value, "inspectionPointTypeCode");
            return (Criteria) this;
        }

        public Criteria andInspectionPointTypeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("inspection_point_type_code >=", value, "inspectionPointTypeCode");
            return (Criteria) this;
        }

        public Criteria andInspectionPointTypeCodeLessThan(String value) {
            addCriterion("inspection_point_type_code <", value, "inspectionPointTypeCode");
            return (Criteria) this;
        }

        public Criteria andInspectionPointTypeCodeLessThanOrEqualTo(String value) {
            addCriterion("inspection_point_type_code <=", value, "inspectionPointTypeCode");
            return (Criteria) this;
        }

        public Criteria andInspectionPointTypeCodeLike(String value) {
            addCriterion("inspection_point_type_code like", value, "inspectionPointTypeCode");
            return (Criteria) this;
        }

        public Criteria andInspectionPointTypeCodeNotLike(String value) {
            addCriterion("inspection_point_type_code not like", value, "inspectionPointTypeCode");
            return (Criteria) this;
        }

        public Criteria andInspectionPointTypeCodeIn(List<String> values) {
            addCriterion("inspection_point_type_code in", values, "inspectionPointTypeCode");
            return (Criteria) this;
        }

        public Criteria andInspectionPointTypeCodeNotIn(List<String> values) {
            addCriterion("inspection_point_type_code not in", values, "inspectionPointTypeCode");
            return (Criteria) this;
        }

        public Criteria andInspectionPointTypeCodeBetween(String value1, String value2) {
            addCriterion("inspection_point_type_code between", value1, value2, "inspectionPointTypeCode");
            return (Criteria) this;
        }

        public Criteria andInspectionPointTypeCodeNotBetween(String value1, String value2) {
            addCriterion("inspection_point_type_code not between", value1, value2, "inspectionPointTypeCode");
            return (Criteria) this;
        }

        public Criteria andInspectionPointNameIsNull() {
            addCriterion("inspection_point_name is null");
            return (Criteria) this;
        }

        public Criteria andInspectionPointNameIsNotNull() {
            addCriterion("inspection_point_name is not null");
            return (Criteria) this;
        }

        public Criteria andInspectionPointNameEqualTo(String value) {
            addCriterion("inspection_point_name =", value, "inspectionPointName");
            return (Criteria) this;
        }

        public Criteria andInspectionPointNameNotEqualTo(String value) {
            addCriterion("inspection_point_name <>", value, "inspectionPointName");
            return (Criteria) this;
        }

        public Criteria andInspectionPointNameGreaterThan(String value) {
            addCriterion("inspection_point_name >", value, "inspectionPointName");
            return (Criteria) this;
        }

        public Criteria andInspectionPointNameGreaterThanOrEqualTo(String value) {
            addCriterion("inspection_point_name >=", value, "inspectionPointName");
            return (Criteria) this;
        }

        public Criteria andInspectionPointNameLessThan(String value) {
            addCriterion("inspection_point_name <", value, "inspectionPointName");
            return (Criteria) this;
        }

        public Criteria andInspectionPointNameLessThanOrEqualTo(String value) {
            addCriterion("inspection_point_name <=", value, "inspectionPointName");
            return (Criteria) this;
        }

        public Criteria andInspectionPointNameLike(String value) {
            addCriterion("inspection_point_name like", value, "inspectionPointName");
            return (Criteria) this;
        }

        public Criteria andInspectionPointNameNotLike(String value) {
            addCriterion("inspection_point_name not like", value, "inspectionPointName");
            return (Criteria) this;
        }

        public Criteria andInspectionPointNameIn(List<String> values) {
            addCriterion("inspection_point_name in", values, "inspectionPointName");
            return (Criteria) this;
        }

        public Criteria andInspectionPointNameNotIn(List<String> values) {
            addCriterion("inspection_point_name not in", values, "inspectionPointName");
            return (Criteria) this;
        }

        public Criteria andInspectionPointNameBetween(String value1, String value2) {
            addCriterion("inspection_point_name between", value1, value2, "inspectionPointName");
            return (Criteria) this;
        }

        public Criteria andInspectionPointNameNotBetween(String value1, String value2) {
            addCriterion("inspection_point_name not between", value1, value2, "inspectionPointName");
            return (Criteria) this;
        }

        public Criteria andMileageNoIsNull() {
            addCriterion("mileage_no is null");
            return (Criteria) this;
        }

        public Criteria andMileageNoIsNotNull() {
            addCriterion("mileage_no is not null");
            return (Criteria) this;
        }

        public Criteria andMileageNoEqualTo(String value) {
            addCriterion("mileage_no =", value, "mileageNo");
            return (Criteria) this;
        }

        public Criteria andMileageNoNotEqualTo(String value) {
            addCriterion("mileage_no <>", value, "mileageNo");
            return (Criteria) this;
        }

        public Criteria andMileageNoGreaterThan(String value) {
            addCriterion("mileage_no >", value, "mileageNo");
            return (Criteria) this;
        }

        public Criteria andMileageNoGreaterThanOrEqualTo(String value) {
            addCriterion("mileage_no >=", value, "mileageNo");
            return (Criteria) this;
        }

        public Criteria andMileageNoLessThan(String value) {
            addCriterion("mileage_no <", value, "mileageNo");
            return (Criteria) this;
        }

        public Criteria andMileageNoLessThanOrEqualTo(String value) {
            addCriterion("mileage_no <=", value, "mileageNo");
            return (Criteria) this;
        }

        public Criteria andMileageNoLike(String value) {
            addCriterion("mileage_no like", value, "mileageNo");
            return (Criteria) this;
        }

        public Criteria andMileageNoNotLike(String value) {
            addCriterion("mileage_no not like", value, "mileageNo");
            return (Criteria) this;
        }

        public Criteria andMileageNoIn(List<String> values) {
            addCriterion("mileage_no in", values, "mileageNo");
            return (Criteria) this;
        }

        public Criteria andMileageNoNotIn(List<String> values) {
            addCriterion("mileage_no not in", values, "mileageNo");
            return (Criteria) this;
        }

        public Criteria andMileageNoBetween(String value1, String value2) {
            addCriterion("mileage_no between", value1, value2, "mileageNo");
            return (Criteria) this;
        }

        public Criteria andMileageNoNotBetween(String value1, String value2) {
            addCriterion("mileage_no not between", value1, value2, "mileageNo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_inspection_point
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_inspection_point
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}