package deepthinking.fgi.domain;

import java.util.Date;

public class TInspectionLine {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_inspection_line.line_code
     *
     * @mbg.generated
     */
    private Integer lineCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_inspection_line.region_code
     *
     * @mbg.generated
     */
    private String regionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_inspection_line.line_name
     *
     * @mbg.generated
     */
    private String lineName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_inspection_line.direction
     *
     * @mbg.generated
     */
    private String direction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_inspection_line.mileage_start
     *
     * @mbg.generated
     */
    private String mileageStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_inspection_line.mileage_end
     *
     * @mbg.generated
     */
    private String mileageEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_inspection_line.completion_date
     *
     * @mbg.generated
     */
    private Date completionDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_inspection_line.operation_date
     *
     * @mbg.generated
     */
    private Date operationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_inspection_line.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_inspection_line.line_code
     *
     * @return the value of t_inspection_line.line_code
     *
     * @mbg.generated
     */
    public Integer getLineCode() {
        return lineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_inspection_line.line_code
     *
     * @param lineCode the value for t_inspection_line.line_code
     *
     * @mbg.generated
     */
    public void setLineCode(Integer lineCode) {
        this.lineCode = lineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_inspection_line.region_code
     *
     * @return the value of t_inspection_line.region_code
     *
     * @mbg.generated
     */
    public String getRegionCode() {
        return regionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_inspection_line.region_code
     *
     * @param regionCode the value for t_inspection_line.region_code
     *
     * @mbg.generated
     */
    public void setRegionCode(String regionCode) {
        this.regionCode = regionCode == null ? null : regionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_inspection_line.line_name
     *
     * @return the value of t_inspection_line.line_name
     *
     * @mbg.generated
     */
    public String getLineName() {
        return lineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_inspection_line.line_name
     *
     * @param lineName the value for t_inspection_line.line_name
     *
     * @mbg.generated
     */
    public void setLineName(String lineName) {
        this.lineName = lineName == null ? null : lineName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_inspection_line.direction
     *
     * @return the value of t_inspection_line.direction
     *
     * @mbg.generated
     */
    public String getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_inspection_line.direction
     *
     * @param direction the value for t_inspection_line.direction
     *
     * @mbg.generated
     */
    public void setDirection(String direction) {
        this.direction = direction == null ? null : direction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_inspection_line.mileage_start
     *
     * @return the value of t_inspection_line.mileage_start
     *
     * @mbg.generated
     */
    public String getMileageStart() {
        return mileageStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_inspection_line.mileage_start
     *
     * @param mileageStart the value for t_inspection_line.mileage_start
     *
     * @mbg.generated
     */
    public void setMileageStart(String mileageStart) {
        this.mileageStart = mileageStart == null ? null : mileageStart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_inspection_line.mileage_end
     *
     * @return the value of t_inspection_line.mileage_end
     *
     * @mbg.generated
     */
    public String getMileageEnd() {
        return mileageEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_inspection_line.mileage_end
     *
     * @param mileageEnd the value for t_inspection_line.mileage_end
     *
     * @mbg.generated
     */
    public void setMileageEnd(String mileageEnd) {
        this.mileageEnd = mileageEnd == null ? null : mileageEnd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_inspection_line.completion_date
     *
     * @return the value of t_inspection_line.completion_date
     *
     * @mbg.generated
     */
    public Date getCompletionDate() {
        return completionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_inspection_line.completion_date
     *
     * @param completionDate the value for t_inspection_line.completion_date
     *
     * @mbg.generated
     */
    public void setCompletionDate(Date completionDate) {
        this.completionDate = completionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_inspection_line.operation_date
     *
     * @return the value of t_inspection_line.operation_date
     *
     * @mbg.generated
     */
    public Date getOperationDate() {
        return operationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_inspection_line.operation_date
     *
     * @param operationDate the value for t_inspection_line.operation_date
     *
     * @mbg.generated
     */
    public void setOperationDate(Date operationDate) {
        this.operationDate = operationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_inspection_line.description
     *
     * @return the value of t_inspection_line.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_inspection_line.description
     *
     * @param description the value for t_inspection_line.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}