package deepthinking.fgi.domain;

import java.util.ArrayList;
import java.util.List;

public class TInstrumentCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_instrument
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_instrument
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_instrument
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_instrument
     *
     * @mbg.generated
     */
    public TInstrumentCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_instrument
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_instrument
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_instrument
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_instrument
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_instrument
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_instrument
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_instrument
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_instrument
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_instrument
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_instrument
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_instrument
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andInstrumentCodeIsNull() {
            addCriterion("instrument_code is null");
            return (Criteria) this;
        }

        public Criteria andInstrumentCodeIsNotNull() {
            addCriterion("instrument_code is not null");
            return (Criteria) this;
        }

        public Criteria andInstrumentCodeEqualTo(String value) {
            addCriterion("instrument_code =", value, "instrumentCode");
            return (Criteria) this;
        }

        public Criteria andInstrumentCodeNotEqualTo(String value) {
            addCriterion("instrument_code <>", value, "instrumentCode");
            return (Criteria) this;
        }

        public Criteria andInstrumentCodeGreaterThan(String value) {
            addCriterion("instrument_code >", value, "instrumentCode");
            return (Criteria) this;
        }

        public Criteria andInstrumentCodeGreaterThanOrEqualTo(String value) {
            addCriterion("instrument_code >=", value, "instrumentCode");
            return (Criteria) this;
        }

        public Criteria andInstrumentCodeLessThan(String value) {
            addCriterion("instrument_code <", value, "instrumentCode");
            return (Criteria) this;
        }

        public Criteria andInstrumentCodeLessThanOrEqualTo(String value) {
            addCriterion("instrument_code <=", value, "instrumentCode");
            return (Criteria) this;
        }

        public Criteria andInstrumentCodeLike(String value) {
            addCriterion("instrument_code like", value, "instrumentCode");
            return (Criteria) this;
        }

        public Criteria andInstrumentCodeNotLike(String value) {
            addCriterion("instrument_code not like", value, "instrumentCode");
            return (Criteria) this;
        }

        public Criteria andInstrumentCodeIn(List<String> values) {
            addCriterion("instrument_code in", values, "instrumentCode");
            return (Criteria) this;
        }

        public Criteria andInstrumentCodeNotIn(List<String> values) {
            addCriterion("instrument_code not in", values, "instrumentCode");
            return (Criteria) this;
        }

        public Criteria andInstrumentCodeBetween(String value1, String value2) {
            addCriterion("instrument_code between", value1, value2, "instrumentCode");
            return (Criteria) this;
        }

        public Criteria andInstrumentCodeNotBetween(String value1, String value2) {
            addCriterion("instrument_code not between", value1, value2, "instrumentCode");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeCodeIsNull() {
            addCriterion("device_type_code is null");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeCodeIsNotNull() {
            addCriterion("device_type_code is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeCodeEqualTo(String value) {
            addCriterion("device_type_code =", value, "deviceTypeCode");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeCodeNotEqualTo(String value) {
            addCriterion("device_type_code <>", value, "deviceTypeCode");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeCodeGreaterThan(String value) {
            addCriterion("device_type_code >", value, "deviceTypeCode");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("device_type_code >=", value, "deviceTypeCode");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeCodeLessThan(String value) {
            addCriterion("device_type_code <", value, "deviceTypeCode");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeCodeLessThanOrEqualTo(String value) {
            addCriterion("device_type_code <=", value, "deviceTypeCode");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeCodeLike(String value) {
            addCriterion("device_type_code like", value, "deviceTypeCode");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeCodeNotLike(String value) {
            addCriterion("device_type_code not like", value, "deviceTypeCode");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeCodeIn(List<String> values) {
            addCriterion("device_type_code in", values, "deviceTypeCode");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeCodeNotIn(List<String> values) {
            addCriterion("device_type_code not in", values, "deviceTypeCode");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeCodeBetween(String value1, String value2) {
            addCriterion("device_type_code between", value1, value2, "deviceTypeCode");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeCodeNotBetween(String value1, String value2) {
            addCriterion("device_type_code not between", value1, value2, "deviceTypeCode");
            return (Criteria) this;
        }

        public Criteria andOrganizationCodeIsNull() {
            addCriterion("organization_code is null");
            return (Criteria) this;
        }

        public Criteria andOrganizationCodeIsNotNull() {
            addCriterion("organization_code is not null");
            return (Criteria) this;
        }

        public Criteria andOrganizationCodeEqualTo(Integer value) {
            addCriterion("organization_code =", value, "organizationCode");
            return (Criteria) this;
        }

        public Criteria andOrganizationCodeNotEqualTo(Integer value) {
            addCriterion("organization_code <>", value, "organizationCode");
            return (Criteria) this;
        }

        public Criteria andOrganizationCodeGreaterThan(Integer value) {
            addCriterion("organization_code >", value, "organizationCode");
            return (Criteria) this;
        }

        public Criteria andOrganizationCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("organization_code >=", value, "organizationCode");
            return (Criteria) this;
        }

        public Criteria andOrganizationCodeLessThan(Integer value) {
            addCriterion("organization_code <", value, "organizationCode");
            return (Criteria) this;
        }

        public Criteria andOrganizationCodeLessThanOrEqualTo(Integer value) {
            addCriterion("organization_code <=", value, "organizationCode");
            return (Criteria) this;
        }

        public Criteria andOrganizationCodeIn(List<Integer> values) {
            addCriterion("organization_code in", values, "organizationCode");
            return (Criteria) this;
        }

        public Criteria andOrganizationCodeNotIn(List<Integer> values) {
            addCriterion("organization_code not in", values, "organizationCode");
            return (Criteria) this;
        }

        public Criteria andOrganizationCodeBetween(Integer value1, Integer value2) {
            addCriterion("organization_code between", value1, value2, "organizationCode");
            return (Criteria) this;
        }

        public Criteria andOrganizationCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("organization_code not between", value1, value2, "organizationCode");
            return (Criteria) this;
        }

        public Criteria andInstrumentNameIsNull() {
            addCriterion("instrument_name is null");
            return (Criteria) this;
        }

        public Criteria andInstrumentNameIsNotNull() {
            addCriterion("instrument_name is not null");
            return (Criteria) this;
        }

        public Criteria andInstrumentNameEqualTo(String value) {
            addCriterion("instrument_name =", value, "instrumentName");
            return (Criteria) this;
        }

        public Criteria andInstrumentNameNotEqualTo(String value) {
            addCriterion("instrument_name <>", value, "instrumentName");
            return (Criteria) this;
        }

        public Criteria andInstrumentNameGreaterThan(String value) {
            addCriterion("instrument_name >", value, "instrumentName");
            return (Criteria) this;
        }

        public Criteria andInstrumentNameGreaterThanOrEqualTo(String value) {
            addCriterion("instrument_name >=", value, "instrumentName");
            return (Criteria) this;
        }

        public Criteria andInstrumentNameLessThan(String value) {
            addCriterion("instrument_name <", value, "instrumentName");
            return (Criteria) this;
        }

        public Criteria andInstrumentNameLessThanOrEqualTo(String value) {
            addCriterion("instrument_name <=", value, "instrumentName");
            return (Criteria) this;
        }

        public Criteria andInstrumentNameLike(String value) {
            addCriterion("instrument_name like", value, "instrumentName");
            return (Criteria) this;
        }

        public Criteria andInstrumentNameNotLike(String value) {
            addCriterion("instrument_name not like", value, "instrumentName");
            return (Criteria) this;
        }

        public Criteria andInstrumentNameIn(List<String> values) {
            addCriterion("instrument_name in", values, "instrumentName");
            return (Criteria) this;
        }

        public Criteria andInstrumentNameNotIn(List<String> values) {
            addCriterion("instrument_name not in", values, "instrumentName");
            return (Criteria) this;
        }

        public Criteria andInstrumentNameBetween(String value1, String value2) {
            addCriterion("instrument_name between", value1, value2, "instrumentName");
            return (Criteria) this;
        }

        public Criteria andInstrumentNameNotBetween(String value1, String value2) {
            addCriterion("instrument_name not between", value1, value2, "instrumentName");
            return (Criteria) this;
        }

        public Criteria andInstrumentModelIsNull() {
            addCriterion("instrument_model is null");
            return (Criteria) this;
        }

        public Criteria andInstrumentModelIsNotNull() {
            addCriterion("instrument_model is not null");
            return (Criteria) this;
        }

        public Criteria andInstrumentModelEqualTo(String value) {
            addCriterion("instrument_model =", value, "instrumentModel");
            return (Criteria) this;
        }

        public Criteria andInstrumentModelNotEqualTo(String value) {
            addCriterion("instrument_model <>", value, "instrumentModel");
            return (Criteria) this;
        }

        public Criteria andInstrumentModelGreaterThan(String value) {
            addCriterion("instrument_model >", value, "instrumentModel");
            return (Criteria) this;
        }

        public Criteria andInstrumentModelGreaterThanOrEqualTo(String value) {
            addCriterion("instrument_model >=", value, "instrumentModel");
            return (Criteria) this;
        }

        public Criteria andInstrumentModelLessThan(String value) {
            addCriterion("instrument_model <", value, "instrumentModel");
            return (Criteria) this;
        }

        public Criteria andInstrumentModelLessThanOrEqualTo(String value) {
            addCriterion("instrument_model <=", value, "instrumentModel");
            return (Criteria) this;
        }

        public Criteria andInstrumentModelLike(String value) {
            addCriterion("instrument_model like", value, "instrumentModel");
            return (Criteria) this;
        }

        public Criteria andInstrumentModelNotLike(String value) {
            addCriterion("instrument_model not like", value, "instrumentModel");
            return (Criteria) this;
        }

        public Criteria andInstrumentModelIn(List<String> values) {
            addCriterion("instrument_model in", values, "instrumentModel");
            return (Criteria) this;
        }

        public Criteria andInstrumentModelNotIn(List<String> values) {
            addCriterion("instrument_model not in", values, "instrumentModel");
            return (Criteria) this;
        }

        public Criteria andInstrumentModelBetween(String value1, String value2) {
            addCriterion("instrument_model between", value1, value2, "instrumentModel");
            return (Criteria) this;
        }

        public Criteria andInstrumentModelNotBetween(String value1, String value2) {
            addCriterion("instrument_model not between", value1, value2, "instrumentModel");
            return (Criteria) this;
        }

        public Criteria andDeviceStatusCodeIsNull() {
            addCriterion("device_status_code is null");
            return (Criteria) this;
        }

        public Criteria andDeviceStatusCodeIsNotNull() {
            addCriterion("device_status_code is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceStatusCodeEqualTo(String value) {
            addCriterion("device_status_code =", value, "deviceStatusCode");
            return (Criteria) this;
        }

        public Criteria andDeviceStatusCodeNotEqualTo(String value) {
            addCriterion("device_status_code <>", value, "deviceStatusCode");
            return (Criteria) this;
        }

        public Criteria andDeviceStatusCodeGreaterThan(String value) {
            addCriterion("device_status_code >", value, "deviceStatusCode");
            return (Criteria) this;
        }

        public Criteria andDeviceStatusCodeGreaterThanOrEqualTo(String value) {
            addCriterion("device_status_code >=", value, "deviceStatusCode");
            return (Criteria) this;
        }

        public Criteria andDeviceStatusCodeLessThan(String value) {
            addCriterion("device_status_code <", value, "deviceStatusCode");
            return (Criteria) this;
        }

        public Criteria andDeviceStatusCodeLessThanOrEqualTo(String value) {
            addCriterion("device_status_code <=", value, "deviceStatusCode");
            return (Criteria) this;
        }

        public Criteria andDeviceStatusCodeLike(String value) {
            addCriterion("device_status_code like", value, "deviceStatusCode");
            return (Criteria) this;
        }

        public Criteria andDeviceStatusCodeNotLike(String value) {
            addCriterion("device_status_code not like", value, "deviceStatusCode");
            return (Criteria) this;
        }

        public Criteria andDeviceStatusCodeIn(List<String> values) {
            addCriterion("device_status_code in", values, "deviceStatusCode");
            return (Criteria) this;
        }

        public Criteria andDeviceStatusCodeNotIn(List<String> values) {
            addCriterion("device_status_code not in", values, "deviceStatusCode");
            return (Criteria) this;
        }

        public Criteria andDeviceStatusCodeBetween(String value1, String value2) {
            addCriterion("device_status_code between", value1, value2, "deviceStatusCode");
            return (Criteria) this;
        }

        public Criteria andDeviceStatusCodeNotBetween(String value1, String value2) {
            addCriterion("device_status_code not between", value1, value2, "deviceStatusCode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_instrument
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_instrument
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}